### ISSUE TITLE
Can't download sm

### ISSUE THREAD

**Issue by lcy19** [SourceMonitor/SM-Info#1]
Hi, thanks for developing software monitor, but now I can't download it from https://www.derpaul.net/SourceMonitor/. 
Can you check it or provide release version on github? thanks again.

**Comment by ThirtySomething** [comment]
Hello @Icy19, I'm sorry for the inconvenience. Can you please check again?

**Comment by ThirtySomething** [comment]
@Icy19 does the download work now? Unless there is no feedback up to now this issue will be closed at the end of the month.

**Comment by michel53** [comment]
Here, the downloads work without problems...

**Comment by ThirtySomething** [comment]
Thanks for the feedback @michel53 - so I'll close this issue now.
